# Generated by Django 6.0.4 on 2026-06-04 03:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_coupon_created_at_remove_order_remark_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='salesperson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='api.salesperson'),
        ),
        migrations.AddField(
            model_name='salesperson',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='itemvariant',
            name='barcode',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
    ]
