# Generated by Django 6.0.4 on 2026-06-06 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_order_remark_order_salesperson_salesperson_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemvariant',
            name='minimum_stock',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='itemvariant',
            name='design',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='itemvariant',
            name='size',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='itemvariant',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name='itemvariant',
            constraint=models.UniqueConstraint(fields=('item', 'size', 'design'), name='unique_item_variant'),
        ),
    ]
