# Generated by Django 6.0.4 on 2026-06-07 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_order_remark_order_salesperson_salesperson_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(choices=[('Door2Door', 'Door to Door'), ('Door2Branch', 'Door to Branch')], default='Door2Door', max_length=20),
        ),
    ]
