# Generated by Django 6.0.4 on 2026-06-13 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_order_delivery_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='packed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone1',
            field=models.CharField(db_index=True, max_length=10, unique=True),
        ),
    ]
