# Generated by Django 6.0.4 on 2026-06-17 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_orderitem_packed_alter_customer_phone1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='packed',
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('packed', 'Packed')], default='pending', max_length=20),
        ),
    ]
