# Generated by Django 6.0.4 on 2026-06-18 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_orderitem_packed_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company/')),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr/')),
                ('address', models.TextField()),
                ('website', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
