# Generated by Django 6.0.4 on 2026-06-22 03:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_change', models.IntegerField()),
                ('reason', models.CharField(choices=[('restock', 'Manual restock'), ('order', 'Order placed'), ('cancellation', 'Order cancelled'), ('correction', 'Manual correction')], max_length=20)),
                ('note', models.TextField(blank=True, null=True)),
                ('stock_after', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.salesperson')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_logs', to='api.itemvariant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
